plugins {
    id 'com.android.library'
}

android {
    compileSdk 33
    defaultConfig {
        minSdk 24
        externalNativeBuild {
            cmake { cppFlags "-std=c++17 -fvisibility=hidden" }
        }
    }
}

// Ensure native libs are copied into the module zip structure
tasks.register('prepareMagiskModule', Copy) {
    from("${buildDir}/intermediates/cmake/release/obj")
    into("${buildDir}/outputs/magisk_module/zygisk")
    include "**/*.so"
}

tasks.named('assembleRelease') { finalizedBy 'prepareMagiskModule' }
