plugins {
    id 'com.android.library'
}

android {
    compileSdkVersion 33
    defaultConfig {
        minSdkVersion 24
        targetSdkVersion 33
        externalNativeBuild {
            cmake {
                cppFlags "-std=c++17 -fvisibility=hidden"
                arguments "-DANDROID_STL=c++_shared"
            }
        }
    }
    
    // Ensure native libraries are packaged into the APK/ZIP
    sourceSets {
        main {
            jniLibs.srcDirs = ['src/main/jniLibs']
        }
    }
}

task zipModule(type: Zip) {
    from('src/main/resources')
    from(layout.buildDirectory.dir("intermediates/cmake/release/obj")) {
        into 'zygisk'
    }
    archiveFileName = "module.zip"
    destinationDirectory = layout.buildDirectory.dir("outputs/zip")
}
