plugins {
    id 'com.android.library'
}

android {
    compileSdk 33

    defaultConfig {
        minSdk 21
        targetSdk 33

        externalNativeBuild {
            cmake {
                cppFlags "-std=c++17 -O3 -fvisibility=hidden -Wall"
                arguments "-DANDROID_STL=c++_static"
                abiFilters 'arm64-v8a', 'armeabi-v7a'
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
        }
    }

    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version "3.22.1"
        }
    }

    packagingOptions {
        exclude '**/libzygisk.so'
    }
}

afterEvaluate {
    def zipTask = tasks.register('zip', Zip) {
        dependsOn 'externalNativeBuildRelease'

        archiveFileName = "Zygisk-ImGui-Menu-v1.0.0.zip"
        destinationDirectory = file("$rootDir/out")

        from("$rootDir/template") {
            include "module.prop"
            include "customize.sh"
            include "service.sh"
        }

        ['arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64'].each { abi ->
            def abiLibDir = file("$buildDir/outputs/zygisk_libs/$abi")
            
            from(abiLibDir) {
                include "libzygisk.so"
                into "zygisk/$abi"
            }
            from(abiLibDir) {
                include "libzygisk.so"
                into "zygisk"
                rename "libzygisk.so", "${abi}.so"
            }
        }
    }

    tasks.named('assemble').configure {
        finalizedBy(zipTask)
    }
}
